version: "3.7"
services:
  lyricsservice:
    build: 
      context: .
      dockerfile: "./LyricsService/Dockerfile"
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
    ports:
      - ${LyricsServicePort}:${LyricsServicePort}
    environment:
      - LyricsServicePort
      - GeniusAccessToken
  spotifyservice:
    environment:
      - SpotifyClientID
      - SpotifyClientSecret
      - SpotifyServicePort
      - SpotifyRedirectURL
      - LyricsServicePort
      - LyricsServiceName
    build:
      context: .
      dockerfile: "./SpotifyService/Dockerfile"
    expose:
      - ${SpotifyServicePort}
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
    depends_on:
      - lyricsservice
  nginx:
    build: 
      context: .
      dockerfile: "./nginx/Dockerfile"
    ports:
      - "80:80"
    depends_on:
      - spotifyservice