// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tracks struct {
	TrackInfo            []*Tracks_TrackInfo `protobuf:"bytes,1,rep,name=trackInfo,proto3" json:"trackInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Tracks) Reset()         { *m = Tracks{} }
func (m *Tracks) String() string { return proto.CompactTextString(m) }
func (*Tracks) ProtoMessage()    {}
func (*Tracks) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Tracks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracks.Unmarshal(m, b)
}
func (m *Tracks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracks.Marshal(b, m, deterministic)
}
func (m *Tracks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracks.Merge(m, src)
}
func (m *Tracks) XXX_Size() int {
	return xxx_messageInfo_Tracks.Size(m)
}
func (m *Tracks) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracks.DiscardUnknown(m)
}

var xxx_messageInfo_Tracks proto.InternalMessageInfo

func (m *Tracks) GetTrackInfo() []*Tracks_TrackInfo {
	if m != nil {
		return m.TrackInfo
	}
	return nil
}

type Tracks_TrackInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artist               string   `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	GeniusURI            string   `protobuf:"bytes,3,opt,name=geniusURI,proto3" json:"geniusURI,omitempty"`
	Lyrics               string   `protobuf:"bytes,4,opt,name=lyrics,proto3" json:"lyrics,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Rank                 int32    `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tracks_TrackInfo) Reset()         { *m = Tracks_TrackInfo{} }
func (m *Tracks_TrackInfo) String() string { return proto.CompactTextString(m) }
func (*Tracks_TrackInfo) ProtoMessage()    {}
func (*Tracks_TrackInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

func (m *Tracks_TrackInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracks_TrackInfo.Unmarshal(m, b)
}
func (m *Tracks_TrackInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracks_TrackInfo.Marshal(b, m, deterministic)
}
func (m *Tracks_TrackInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracks_TrackInfo.Merge(m, src)
}
func (m *Tracks_TrackInfo) XXX_Size() int {
	return xxx_messageInfo_Tracks_TrackInfo.Size(m)
}
func (m *Tracks_TrackInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracks_TrackInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Tracks_TrackInfo proto.InternalMessageInfo

func (m *Tracks_TrackInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tracks_TrackInfo) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *Tracks_TrackInfo) GetGeniusURI() string {
	if m != nil {
		return m.GeniusURI
	}
	return ""
}

func (m *Tracks_TrackInfo) GetLyrics() string {
	if m != nil {
		return m.Lyrics
	}
	return ""
}

func (m *Tracks_TrackInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tracks_TrackInfo) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func init() {
	proto.RegisterType((*Tracks)(nil), "api.Tracks")
	proto.RegisterType((*Tracks_TrackInfo)(nil), "api.Tracks.TrackInfo")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xba, 0xc8, 0xc8, 0xc5, 0x16,
	0x52, 0x94, 0x98, 0x9c, 0x5d, 0x2c, 0x64, 0xcc, 0xc5, 0x59, 0x02, 0x62, 0x79, 0xe6, 0xa5, 0xe5,
	0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xea, 0x81, 0x94, 0x43, 0xe4, 0x21, 0x14, 0x48,
	0x32, 0x08, 0xa1, 0x4e, 0x6a, 0x22, 0x23, 0x17, 0x27, 0x5c, 0x42, 0x48, 0x88, 0x8b, 0x25, 0x2f,
	0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe3, 0x62, 0x4b,
	0x2c, 0x2a, 0xc9, 0x2c, 0x2e, 0x91, 0x60, 0x02, 0x8b, 0x42, 0x79, 0x42, 0x32, 0x5c, 0x9c, 0xe9,
	0xa9, 0x79, 0x99, 0xa5, 0xc5, 0xa1, 0x41, 0x9e, 0x12, 0xcc, 0x60, 0x29, 0x84, 0x00, 0x48, 0x57,
	0x4e, 0x65, 0x51, 0x66, 0x72, 0xb1, 0x04, 0x0b, 0x44, 0x17, 0x84, 0x27, 0xc4, 0xc7, 0xc5, 0x94,
	0x99, 0x22, 0xc1, 0x0a, 0x16, 0x63, 0xca, 0x4c, 0x01, 0xd9, 0x58, 0x94, 0x98, 0x97, 0x2d, 0xc1,
	0xa6, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x66, 0x1b, 0x19, 0x72, 0xb1, 0xf9, 0x40, 0x54, 0xab, 0x73,
	0x71, 0xba, 0xa7, 0x96, 0x40, 0x39, 0xdc, 0x48, 0x9e, 0x91, 0x42, 0xe6, 0x28, 0x31, 0x24, 0xb1,
	0x81, 0x83, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x76, 0xc6, 0x7a, 0x1f, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LyricsClient is the client API for Lyrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LyricsClient interface {
	GetLyrics(ctx context.Context, in *Tracks, opts ...grpc.CallOption) (*Tracks, error)
}

type lyricsClient struct {
	cc *grpc.ClientConn
}

func NewLyricsClient(cc *grpc.ClientConn) LyricsClient {
	return &lyricsClient{cc}
}

func (c *lyricsClient) GetLyrics(ctx context.Context, in *Tracks, opts ...grpc.CallOption) (*Tracks, error) {
	out := new(Tracks)
	err := c.cc.Invoke(ctx, "/api.Lyrics/GetLyrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LyricsServer is the server API for Lyrics service.
type LyricsServer interface {
	GetLyrics(context.Context, *Tracks) (*Tracks, error)
}

// UnimplementedLyricsServer can be embedded to have forward compatible implementations.
type UnimplementedLyricsServer struct {
}

func (*UnimplementedLyricsServer) GetLyrics(ctx context.Context, req *Tracks) (*Tracks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLyrics not implemented")
}

func RegisterLyricsServer(s *grpc.Server, srv LyricsServer) {
	s.RegisterService(&_Lyrics_serviceDesc, srv)
}

func _Lyrics_GetLyrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tracks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LyricsServer).GetLyrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Lyrics/GetLyrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LyricsServer).GetLyrics(ctx, req.(*Tracks))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lyrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Lyrics",
	HandlerType: (*LyricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLyrics",
			Handler:    _Lyrics_GetLyrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
